name: stream_etm_base
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.0
  - _sysroot_linux-64_curr_repodata_hack=3
  - asttokens=2.4.1
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40.0
  - blas=1.0
  - bwidget=1.9.16
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.9.24
  - cairo=1.16.0
  - cffi=1.17.1
  - comm=0.2.2
  - curl=8.9.1
  - debugpy=1.8.9
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.3
  - fontconfig=2.14.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gfortran_impl_linux-64=11.2.0
  - gfortran_linux-64=11.2.0
  - glib=2.78.4
  - glib-tools=2.78.4
  - graphite2=1.3.14
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - harfbuzz=4.3.0
  - icu=73.1
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.29.0
  - jedi=0.19.2
  - jinja2=3.1.4
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kernel-headers_linux-64=3.10.0
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libblas=3.9.0
  - libcurl=8.9.1
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libssh2=1.11.0
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.13.1
  - lz4-c=1.9.4
  - make=4.2.1
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.4.0
  - packaging=24.2
  - pandoc=3.5
  - pango=1.50.7
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - pixman=0.40.0
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.21
  - pygments=2.18.0
  - python=3.11.10
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pytz=2024.1
  - pyzmq=26.2.0
  - r-askpass=1.2.1
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base=4.3.1
  - r-base64enc=0.1_3
  - r-bit=4.5.0
  - r-bit64=4.5.2
  - r-blob=1.2.4
  - r-broom=1.0.7
  - r-bslib=0.8.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-cellranger=1.1.0
  - r-cli=3.6.3
  - r-clipr=0.8.0
  - r-colorspace=2.1_1
  - r-conflicted=1.2.0
  - r-cpp11=0.5.0
  - r-crayon=1.5.3
  - r-curl=5.2.1
  - r-data.table=1.14.8
  - r-dbi=1.2.3
  - r-dbplyr=2.5.0
  - r-digest=0.6.37
  - r-dplyr=1.1.4
  - r-dtplyr=1.3.1
  - r-ellipsis=0.3.2
  - r-evaluate=1.0.1
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastmap=1.2.0
  - r-fontawesome=0.5.3
  - r-forcats=1.0.0
  - r-fs=1.6.5
  - r-gargle=1.5.2
  - r-generics=0.1.3
  - r-ggplot2=3.5.1
  - r-glue=1.8.0
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gtable=0.3.6
  - r-haven=2.5.4
  - r-highr=0.11
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-httr=1.4.7
  - r-ids=1.0.1
  - r-isoband=0.2.7
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.9
  - r-knitr=1.49
  - r-labeling=0.4.3
  - r-lattice=0.22_6
  - r-lifecycle=1.0.4
  - r-lubridate=1.9.3
  - r-magrittr=2.0.3
  - r-mass=7.3_60.0.1
  - r-matrix=1.6_5
  - r-memoise=2.0.1
  - r-mgcv=1.9_1
  - r-mime=0.12
  - r-modelr=0.1.11
  - r-munsell=0.5.1
  - r-nlme=3.1_163
  - r-openssl=2.2.2
  - r-pillar=1.9.0
  - r-pkgconfig=2.0.3
  - r-prettyunits=1.2.0
  - r-processx=3.8.4
  - r-progress=1.2.3
  - r-ps=1.8.1
  - r-purrr=1.0.2
  - r-r6=2.5.1
  - r-ragg=1.2.6
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-readr=2.1.5
  - r-readxl=1.4.3
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-reprex=2.1.1
  - r-rlang=1.1.4
  - r-rmarkdown=2.29
  - r-rstudioapi=0.17.1
  - r-rvest=1.0.4
  - r-sass=0.4.9
  - r-scales=1.3.0
  - r-selectr=0.4_2
  - r-stringi=1.7.12
  - r-stringr=1.5.1
  - r-sys=3.4.3
  - r-systemfonts=1.1.0
  - r-textshaping=0.3.7
  - r-tibble=3.2.1
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-tinytex=0.54
  - r-tzdb=0.4.0
  - r-utf8=1.2.4
  - r-uuid=1.2_1
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.5
  - r-withr=3.0.2
  - r-xfun=0.48
  - r-xml2=1.3.6
  - r-yaml=2.3.10
  - readline=8.2
  - rpy2=3.5.11
  - setuptools=75.1.0
  - simplegeneric=0.8.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - sysroot_linux-64=2.17
  - tk=8.6.14
  - tktable=2.10
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzlocal=5.2
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - attrs==24.2.0
      - bertopic==0.16.4
      - blis==1.0.1
      - catalogue==2.0.10
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cloudpathlib==0.20.0
      - confection==0.1.5
      - contourpy==1.3.1
      - cycler==0.12.1
      - cymem==2.0.8
      - en-core-web-lg==3.8.0
      - en-core-web-md==3.8.0
      - fastjsonschema==2.20.0
      - filelock==3.16.1
      - fonttools==4.55.0
      - fsspec==2024.10.0
      - gensim==4.3.3
      - hdbscan==0.8.40
      - huggingface-hub==0.26.2
      - idna==3.10
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.7
      - langcodes==3.5.0
      - language-data==1.3.0
      - llvmlite==0.43.0
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - murmurhash==1.0.10
      - nbformat==5.10.4
      - networkx==3.4.2
      - nltk==3.9.1
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - pandas==2.2.3
      - pillow==11.0.0
      - plotly==5.24.1
      - pot==0.9.5
      - preshed==3.0.9
      - pydantic==2.10.1
      - pydantic-core==2.27.1
      - pynndescent==0.5.13
      - pyparsing==3.2.0
      - pyyaml==6.0.2
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.21.0
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - seaborn==0.13.2
      - sentence-transformers==3.3.1
      - shellingham==1.5.4
      - smart-open==7.0.5
      - spacy==3.8.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - sympy==1.13.1
      - tenacity==9.0.0
      - thinc==8.3.2
      - threadpoolctl==3.5.0
      - tokenizers==0.20.3
      - torch==2.5.1
      - tqdm==4.67.0
      - transformers==4.46.3
      - triton==3.1.0
      - typer==0.13.1
      - tzdata==2024.2
      - umap-learn==0.5.7
      - urllib3==2.2.3
      - wasabi==1.1.3
      - weasel==0.4.1
      - wrapt==1.17.0
